// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Work = Collections['work']['schema']['_output']
export declare const work: Work[]

export type Recipe = Collections['recipe']['schema']['_output']
export declare const recipe: Recipe[]
