packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@vercel/speed-insights'
  - core-js
  - cypress
  - esbuild
  - sharp
  - turbo
  - turbo-darwin-arm64
  - unrs-resolver
  - workerd

sideEffectsCache: false

catalog:
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  react: 19.2.0
  react-dom: 19.2.0
  next: 16.0.0-beta.0
