packages:
  - apps/*
  - packages/*

catalog:
  '@ariakit/react': 0.4.19
  '@biomejs/biome': 2.3.5
  '@types/react': 19.2.5
  '@types/react-dom': 19.2.3
  next: 16.0.3
  nuqs: 2.7.3
  react: 19.2.0
  react-dom: 19.2.0
  typescript: 5.9.3
  vite: 7.2.2
  vitest: 4.0.9

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@swc/core'
  - '@vercel/speed-insights'
  - core-js
  - core-js-pure
  - cypress
  - esbuild
  - sharp
  - turbo
  - turbo-darwin-arm64
  - unrs-resolver
  - workerd

sideEffectsCache: false
