packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@vercel/speed-insights'
  - core-js
  - cypress
  - esbuild
  - sharp
  - turbo
  - turbo-darwin-arm64
  - unrs-resolver
  - workerd

sideEffectsCache: false
linkWorkspacePackages: true

catalog:
  react: 19.2.0
  react-dom: 19.2.0
  next: 15.5.4
  nuqs: 2.7.1
