packages:
  - apps/*
  - packages/*

catalog:
  '@ariakit/react': 0.4.21
  '@biomejs/biome': 2.4.4
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  next: 16.1.6
  nuqs: 2.8.2
  react: 19.2.4
  react-dom: 19.2.4
  typescript: 5.9.3
  vite: 7.2.4
  vitest: 4.0.9

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@swc/core'
  - '@vercel/speed-insights'
  - core-js
  - core-js-pure
  - cypress
  - esbuild
  - sharp
  - turbo
  - turbo-darwin-arm64
  - unrs-resolver
  - workerd

sideEffectsCache: false
