name: Auto merge

# **What it does**: Automatically merge pull requests from dependabot.
# **Why we have it**: To keep our dependencies up-to-date, to avoid security issues.
# **Who does it impact**: It helps me focus on higher value work.

on:
  pull_request:
    paths:
      - 'package*.json'
      - '.github/workflows/**'

jobs:
  run:
    name: Dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge Dependency Updates
        uses: tjenkinson/gh-action-auto-merge-dependency-updates@v1.1.1
        with:
          repo-token: ${{ secrets.GH_MERGE_PAT }}
          allowed-actors: dependabot[bot], jacoblapworth
          approve: false
          merge-method: merge
