name: Auto merge

# **What it does**: Automatically merge pull requests from dependabot.
# **Why we have it**: To keep our dependencies up-to-date, to avoid security issues.
# **Who does it impact**: It helps me focus on higher value work.

on:
  pull_request:
    paths:
      - 'package*.json'
      - '.github/workflows/**'
  pull_request_review:
    types:
      - edited
      - submitted

jobs:
  run:
    name: Dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge Dependency Updates
        uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
