name: Deploy

on:
  push:
    branches:
      - development

jobs:
  pull-request:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_assignee: 'jacoblapworth'
