name: CI
on:
  pull_request:
  workflow_dispatch:
env:
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Use Node
        uses: actions/setup-node@v6.2.0
        with:
          node-version-file: package.json
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Pull Vercel Environment Variables
        run: |
          pnpm dlx vercel@latest env pull .env.local --token=${{ secrets.VERCEL_TOKEN }} --yes
        working-directory: apps/web
        env:
          VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}

      - name: Next build cache
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Build
        run: pnpm run build

      - name: Project cache
        uses: actions/cache@v5
        with:
          path: |
            ${{ github.workspace }}/*
          key: ${{ github.sha }}

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Use Node
        uses: actions/setup-node@v6.2.0
        with:
          node-version-file: package.json
          cache: 'pnpm'

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint:ci

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Use Node
        uses: actions/setup-node@v6.2.0
        with:
          node-version-file: package.json
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm playwright install --with-deps chromium
        working-directory: apps/web

      - name: Pull Vercel Environment Variables
        run: |
          pnpm dlx vercel@latest env pull .env.local --token=${{ secrets.VERCEL_TOKEN }} --yes
        working-directory: apps/web
        env:
          VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}

      - name: Build
        run: pnpm run build

      - name: Start server
        run: pnpm run start &
        working-directory: apps/web

      - name: Wait for server
        run: pnpm wait-on http://localhost:3000
        working-directory: apps/web

      - name: Playwright
        run: pnpm playwright test
        working-directory: apps/web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: apps/web/playwright-report/
          retention-days: 30

  Success:
    runs-on: ubuntu-latest
    needs: [Build, Lint, Test]
    if: always()
    steps:
      - run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) }}
      - name: Assign dependabot failures
        run: gh pr edit ${{ github.event.pull_request.number }} --add-assignee "jacoblapworth"
        if: ${{ failure() && github.actor == 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
